# Generated by Django 4.1.2 on 2022-11-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('date_booked', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Booked', 'Booked')], max_length=45, null=True)),
                ('bookings_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('exhibition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('curator_name', models.CharField(max_length=45)),
                ('exhibition_title', models.CharField(max_length=200)),
                ('exhibition_year', models.IntegerField()),
            ],
            options={
                'db_table': 'exhibitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiftShopInventory',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=45, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity_instock', models.IntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'gift_shop_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiftShopTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity_sold', models.IntegerField()),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('register_id', models.CharField(max_length=45)),
                ('emp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'gift_shop_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(blank=True, max_length=45, null=True)),
                ('member_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('member_email', models.CharField(blank=True, max_length=45, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_price', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
