# Generated by Django 4.1.2 on 2022-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTable',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'artist_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('art_piece_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('museum_inventorycol', models.CharField(max_length=45)),
                ('art_type', models.CharField(blank=True, max_length=45, null=True)),
                ('art_piece_name', models.CharField(max_length=45, unique=True)),
                ('artist_name', models.CharField(blank=True, max_length=45, null=True)),
                ('out_on_loan', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'arts',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GiftShopInventory',
        ),
        migrations.DeleteModel(
            name='GiftShopTransaction',
        ),
    ]
