# Generated by Django 4.1.3 on 2022-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('art_piece_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('museum_inventorycol', models.CharField(max_length=45)),
                ('art_type', models.CharField(blank=True, max_length=45, null=True)),
                ('art_piece_name', models.CharField(max_length=45, unique=True)),
                ('art_origin', models.CharField(blank=True, max_length=45, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=45, null=True)),
                ('date_created', models.CharField(max_length=45)),
                ('out_on_loan', models.CharField(max_length=15)),
                ('art_description', models.CharField(blank=True, max_length=45, null=True)),
                ('date_acquired', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'art_piece',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ArtPiece',
        ),
    ]
